from Graph import Graph

test = Graph(True, True)
test.addVertex("Wroclaw")
test.addVertex("Poznan")
test.addVertex("Krzyz")
test.addVertex("Leszno")
test.addVertex("Katowice")
test.addVertex("Krakow")
test.addVertex("Warszawa")
test.addVertex("Gorzow")
test.addVertex("Zielona Gora")
test.addVertex("Kostrzyn")
test.addVertex("Berlin")
test.addVertex("Gdansk")
test.addVertex("Gdynia")
test.addVertex("Sopot")
test.addVertex("Frankfurt")
test.addVertex("Swiebodzin")
test.addVertex("Lubin")
test.addVertex("Lodz")
test.addVertex("Kielce")
test.addVertex("Radom")
test.addVertex("Lublin")
test.addVertex("Rzeszow")
